# Generated by Django 2.2.1 on 2019-05-26 22:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfilpaciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.CharField(default='Paciente', max_length=20)),
                ('ci', models.IntegerField()),
                ('fecha_naci', models.DateField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photospaciente')),
                ('codigoqr', models.ImageField(blank=True, null=True, upload_to='codigos_qr')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
